<?php  exit();
/*
Page: /dede/content_list.php?channelid=17
Error: Incorrect table name '' <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `` arc
 WHERE arc.channel > 0  AND arc.arcrank > -2 LIMIT 0,1;</font>
Time2018-03-14 11:29:50
*/
?>
<?php  exit();
/*
Page: /dede/content_list.php?channelid=17
Error: Incorrect table name '' <br />Error sql: <font color='red'>SELECT arc.id,arc.typeid,arc.senddate,arc.flag,arc.ismake,
arc.channel,arc.arcrank,arc.click,arc.title,arc.color,arc.litpic,arc.pubdate,arc.mid
FROM `` arc
 WHERE arc.channel > 0  AND arc.arcrank > -2 
ORDER BY arc.id DESC LIMIT 0,30</font>
Time2018-03-14 11:29:50
*/
?>
<?php  exit();
/*
Page: /dede/content_list.php?channelid=17
Error: Incorrect table name '' <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `` arc
 WHERE arc.channel > 0  AND arc.arcrank > -2 LIMIT 0,1;</font>
Time2018-03-14 11:29:50
*/
?>
<?php  exit();
/*
Page: /dede/content_list.php?channelid=17
Error: Incorrect table name '' <br />Error sql: <font color='red'>SELECT arc.id,arc.typeid,arc.senddate,arc.flag,arc.ismake,
arc.channel,arc.arcrank,arc.click,arc.title,arc.color,arc.litpic,arc.pubdate,arc.mid
FROM `` arc
 WHERE arc.channel > 0  AND arc.arcrank > -2 
ORDER BY arc.id DESC LIMIT 0,30</font>
Time2018-03-14 11:29:50
*/
?>
<?php  exit();
/*
Page: /dede/content_list.php?channelid=17
Error: Incorrect table name '' <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `` arc
 WHERE arc.channel > 0  AND arc.arcrank > -2 LIMIT 0,1;</font>
Time2018-03-14 11:30:35
*/
?>
<?php  exit();
/*
Page: /dede/content_list.php?channelid=17
Error: Incorrect table name '' <br />Error sql: <font color='red'>SELECT arc.id,arc.typeid,arc.senddate,arc.flag,arc.ismake,
arc.channel,arc.arcrank,arc.click,arc.title,arc.color,arc.litpic,arc.pubdate,arc.mid
FROM `` arc
 WHERE arc.channel > 0  AND arc.arcrank > -2 
ORDER BY arc.id DESC LIMIT 0,30</font>
Time2018-03-14 11:30:35
*/
?>
<?php  exit();
/*
Page: /dede/content_list.php?channelid=17
Error: Incorrect table name '' <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `` arc
 WHERE arc.channel > 0  AND arc.arcrank > -2 LIMIT 0,1;</font>
Time2018-03-14 11:30:35
*/
?>
<?php  exit();
/*
Page: /dede/content_list.php?channelid=17
Error: Incorrect table name '' <br />Error sql: <font color='red'>SELECT arc.id,arc.typeid,arc.senddate,arc.flag,arc.ismake,
arc.channel,arc.arcrank,arc.click,arc.title,arc.color,arc.litpic,arc.pubdate,arc.mid
FROM `` arc
 WHERE arc.channel > 0  AND arc.arcrank > -2 
ORDER BY arc.id DESC LIMIT 0,30</font>
Time2018-03-14 11:30:35
*/
?>
