
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add_new.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='科室' ischannel='1' link='content_list.php?channelid=18' linkadd='archives_add_new.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='体检' ischannel='1' link='content_list.php?channelid=19' linkadd='archives_add_new.php?channelid=19' channelid='19' rank='' target='main' />
  <m:item name='专家' ischannel='1' link='content_list.php?channelid=21' linkadd='archives_add_new.php?channelid=21' channelid='21' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
