
<field:name itemname="套餐名称" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:name>

<field:sub_name itemname="套餐子标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:sub_name>

<field:old_price itemname="原价" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:old_price>
