
<field:expert_name itemname="专家姓名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:expert_name>

<field:position itemname="请填写职务(如**科副主任)" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:position>

<field:describe itemname="简介" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="10000" page="">
</field:describe>
