<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:title itemname="文章标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:title>

<field:create_time itemname="创建时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:create_time>

<field:view_num itemname="浏览次数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:view_num>

<field:source itemname="发布来源" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="本站原创"  maxlength="250" page="">
</field:source>
